
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("1bcf1af0-051f-413e-97e5-a6e02e187261")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("NWindModel", "CategoryProduct", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(NWindModel.Category), "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(NWindModel.Product), True)>

#End Region

Namespace NWindModel

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class NWindEntities
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new NWindEntities object using the connection string found in the 'NWindEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=NWindEntities", "NWindEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new NWindEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "NWindEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new NWindEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "NWindEntities")
            MyBase.ContextOptions.LazyLoadingEnabled = true
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Categories() As ObjectSet(Of Category)
            Get
                If (_Categories Is Nothing) Then
                    _Categories = MyBase.CreateObjectSet(Of Category)("Categories")
                End If
                Return _Categories
            End Get
        End Property
    
        Private _Categories As ObjectSet(Of Category)
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Products() As ObjectSet(Of Product)
            Get
                If (_Products Is Nothing) Then
                    _Products = MyBase.CreateObjectSet(Of Product)("Products")
                End If
                Return _Products
            End Get
        End Property
    
        Private _Products As ObjectSet(Of Product)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToCategories(ByVal category As Category)
            MyBase.AddObject("Categories", category)
        End Sub
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToProducts(ByVal product As Product)
            MyBase.AddObject("Products", product)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="NWindModel", Name:="Category")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Category
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Category object.
        ''' </summary>
        ''' <param name="categoryID">Initial value of the CategoryID property.</param>
        ''' <param name="categoryName">Initial value of the CategoryName property.</param>
        Public Shared Function CreateCategory(categoryID As Global.System.Int32, categoryName As Global.System.String) As Category
            Dim category as Category = New Category
            category.CategoryID = categoryID
            category.CategoryName = categoryName
            Return category
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CategoryID() As Global.System.Int32
            Get
                Return _CategoryID
            End Get
            Set
                If (_CategoryID <> Value) Then
                    OnCategoryIDChanging(value)
                    ReportPropertyChanging("CategoryID")
                    _CategoryID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("CategoryID")
                    OnCategoryIDChanged()
                End If
            End Set
        End Property
    
        Private _CategoryID As Global.System.Int32
        Private Partial Sub OnCategoryIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnCategoryIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CategoryName() As Global.System.String
            Get
                Return _CategoryName
            End Get
            Set
                OnCategoryNameChanging(value)
                ReportPropertyChanging("CategoryName")
                _CategoryName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("CategoryName")
                OnCategoryNameChanged()
            End Set
        End Property
    
        Private _CategoryName As Global.System.String
        Private Partial Sub OnCategoryNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnCategoryNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Description() As Global.System.String
            Get
                Return _Description
            End Get
            Set
                OnDescriptionChanging(value)
                ReportPropertyChanging("Description")
                _Description = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Description")
                OnDescriptionChanged()
            End Set
        End Property
    
        Private _Description As Global.System.String
        Private Partial Sub OnDescriptionChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnDescriptionChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Picture() As Global.System.Byte()
            Get
                    Return StructuralObject.GetValidValue(_Picture)
            End Get
            Set
                OnPictureChanging(value)
                ReportPropertyChanging("Picture")
                _Picture = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("Picture")
                OnPictureChanged()
            End Set
        End Property
    
        Private _Picture As Global.System.Byte()
        Private Partial Sub OnPictureChanging(value As Global.System.Byte())
        End Sub
    
        Private Partial Sub OnPictureChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("NWindModel", "CategoryProduct", "Product")>
         Public Property Products() As EntityCollection(Of Product)
            Get
                Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Product)("NWindModel.CategoryProduct", "Product")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Product)("NWindModel.CategoryProduct", "Product", value)
                End If
            End Set
        End Property

        #End Region

    End Class
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="NWindModel", Name:="Product")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Product
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Product object.
        ''' </summary>
        ''' <param name="productID">Initial value of the ProductID property.</param>
        ''' <param name="productName">Initial value of the ProductName property.</param>
        ''' <param name="categoryID">Initial value of the CategoryID property.</param>
        ''' <param name="discontinued">Initial value of the Discontinued property.</param>
        Public Shared Function CreateProduct(productID As Global.System.Int32, productName As Global.System.String, categoryID As Global.System.Int32, discontinued As Global.System.Boolean) As Product
            Dim product as Product = New Product
            product.ProductID = productID
            product.ProductName = productName
            product.CategoryID = categoryID
            product.Discontinued = discontinued
            Return product
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ProductID() As Global.System.Int32
            Get
                Return _ProductID
            End Get
            Set
                If (_ProductID <> Value) Then
                    OnProductIDChanging(value)
                    ReportPropertyChanging("ProductID")
                    _ProductID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("ProductID")
                    OnProductIDChanged()
                End If
            End Set
        End Property
    
        Private _ProductID As Global.System.Int32
        Private Partial Sub OnProductIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnProductIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property ProductName() As Global.System.String
            Get
                Return _ProductName
            End Get
            Set
                OnProductNameChanging(value)
                ReportPropertyChanging("ProductName")
                _ProductName = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("ProductName")
                OnProductNameChanged()
            End Set
        End Property
    
        Private _ProductName As Global.System.String
        Private Partial Sub OnProductNameChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnProductNameChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property SupplierID() As Nullable(Of Global.System.Int32)
            Get
                Return _SupplierID
            End Get
            Set
                OnSupplierIDChanging(value)
                ReportPropertyChanging("SupplierID")
                _SupplierID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("SupplierID")
                OnSupplierIDChanged()
            End Set
        End Property
    
        Private _SupplierID As Nullable(Of Global.System.Int32)
        Private Partial Sub OnSupplierIDChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnSupplierIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property CategoryID() As Global.System.Int32
            Get
                Return _CategoryID
            End Get
            Set
                OnCategoryIDChanging(value)
                ReportPropertyChanging("CategoryID")
                _CategoryID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CategoryID")
                OnCategoryIDChanged()
            End Set
        End Property
    
        Private _CategoryID As Global.System.Int32
        Private Partial Sub OnCategoryIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnCategoryIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property QuantityPerUnit() As Global.System.String
            Get
                Return _QuantityPerUnit
            End Get
            Set
                OnQuantityPerUnitChanging(value)
                ReportPropertyChanging("QuantityPerUnit")
                _QuantityPerUnit = StructuralObject.SetValidValue(value, true)
                ReportPropertyChanged("QuantityPerUnit")
                OnQuantityPerUnitChanged()
            End Set
        End Property
    
        Private _QuantityPerUnit As Global.System.String
        Private Partial Sub OnQuantityPerUnitChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnQuantityPerUnitChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property UnitPrice() As Nullable(Of Global.System.Decimal)
            Get
                Return _UnitPrice
            End Get
            Set
                OnUnitPriceChanging(value)
                ReportPropertyChanging("UnitPrice")
                _UnitPrice = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("UnitPrice")
                OnUnitPriceChanged()
            End Set
        End Property
    
        Private _UnitPrice As Nullable(Of Global.System.Decimal)
        Private Partial Sub OnUnitPriceChanging(value As Nullable(Of Global.System.Decimal))
        End Sub
    
        Private Partial Sub OnUnitPriceChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property UnitsInStock() As Nullable(Of Global.System.Int16)
            Get
                Return _UnitsInStock
            End Get
            Set
                OnUnitsInStockChanging(value)
                ReportPropertyChanging("UnitsInStock")
                _UnitsInStock = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("UnitsInStock")
                OnUnitsInStockChanged()
            End Set
        End Property
    
        Private _UnitsInStock As Nullable(Of Global.System.Int16)
        Private Partial Sub OnUnitsInStockChanging(value As Nullable(Of Global.System.Int16))
        End Sub
    
        Private Partial Sub OnUnitsInStockChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property UnitsOnOrder() As Nullable(Of Global.System.Int16)
            Get
                Return _UnitsOnOrder
            End Get
            Set
                OnUnitsOnOrderChanging(value)
                ReportPropertyChanging("UnitsOnOrder")
                _UnitsOnOrder = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("UnitsOnOrder")
                OnUnitsOnOrderChanged()
            End Set
        End Property
    
        Private _UnitsOnOrder As Nullable(Of Global.System.Int16)
        Private Partial Sub OnUnitsOnOrderChanging(value As Nullable(Of Global.System.Int16))
        End Sub
    
        Private Partial Sub OnUnitsOnOrderChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property ReorderLevel() As Nullable(Of Global.System.Int16)
            Get
                Return _ReorderLevel
            End Get
            Set
                OnReorderLevelChanging(value)
                ReportPropertyChanging("ReorderLevel")
                _ReorderLevel = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ReorderLevel")
                OnReorderLevelChanged()
            End Set
        End Property
    
        Private _ReorderLevel As Nullable(Of Global.System.Int16)
        Private Partial Sub OnReorderLevelChanging(value As Nullable(Of Global.System.Int16))
        End Sub
    
        Private Partial Sub OnReorderLevelChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property Discontinued() As Global.System.Boolean
            Get
                Return _Discontinued
            End Get
            Set
                OnDiscontinuedChanging(value)
                ReportPropertyChanging("Discontinued")
                _Discontinued = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Discontinued")
                OnDiscontinuedChanged()
            End Set
        End Property
    
        Private _Discontinued As Global.System.Boolean
        Private Partial Sub OnDiscontinuedChanging(value As Global.System.Boolean)
        End Sub
    
        Private Partial Sub OnDiscontinuedChanged()
        End Sub

        #End Region

        #Region "Navigation Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <XmlIgnoreAttribute()>
        <SoapIgnoreAttribute()>
        <DataMemberAttribute()>
        <EdmRelationshipNavigationPropertyAttribute("NWindModel", "CategoryProduct", "Category")>
        Public Property Category() As Category
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("NWindModel.CategoryProduct", "Category").Value
            End Get
            Set
                CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("NWindModel.CategoryProduct", "Category").Value = value
            End Set
        End Property
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <BrowsableAttribute(False)>
        <DataMemberAttribute()>
        Public Property CategoryReference() As EntityReference(Of Category)
            Get
                Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Category)("NWindModel.CategoryProduct", "Category")
            End Get
            Set
                If (Not value Is Nothing)
                    CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Category)("NWindModel.CategoryProduct", "Category", value)
                End If
            End Set
        End Property

        #End Region

    End Class

    #End Region

    
End Namespace
